#!/bin/bash

###########################################
#   Will update this repo to the latest   #
#   on origin/main                        #
###########################################

source ~/bash-helpers/_colours

echo "Updating bash-helpers repo..."

originalPwd=$(pwd)
cd ~/bash-helpers || exit

git checkout main
git pull

echo "${GREEN}Bash helpers updated! Returning to original directory.${RESTORE}"

cd "$originalPwd" || exit
