#!/bin/bash

####################################################
#   Creates a new branch and pushes it to origin   #
#   using the script gitPushSetUpstream            #
####################################################

source ~/bash-helpers/_colours

# The new branch name we are creating must be passed as variable 1, ensure a name is passed
branchName=$1
if [ -z "$branchName" ]; then
  echo "${RED}Error: You must pass a branch name as the first parameter to this script."
  exit 1
fi

echo "Creating new branch: ${LMAGENTA}${branchName}${RESTORE}"
git branch "$branchName" && git checkout "$branchName"

# Branch created, use the gitPushSetUpstream script to push the branch to origin as it asks the user to confirm the name
if ! gitPushSetUpstream; then
  # If they say no to pushing the branch, delete the local branch automatically
  echo "${RED}Incorrect branch name. Deleting local git branch...${RESTORE}"
  sleep 1
  gitDeleteBranchLocal "$branchName"
fi
