#!/bin/bash

#############################################
#   Finds and removes every node_modules    #
#   folder in a monorepo, then performs a   #
#   fresh pnpm install                      #
#############################################

source ~/bin/_colours

originalPwd=$(pwd)
currentDir=${originalPwd##*/}

# First parameter must contain the root directory, otherwise exit
rootDir=$1
# Alternatively, set a default rootDir here, e.g. arg1=$1; rootDir="${arg1:-your-repo-name}"
if [ -z "$rootDir" ]; then
  echo "${RED}You must provide the root directory as the first parameter.${RESTORE}"
  exit 1
fi

# If pwd does not contain rootDir then exit
if [[ "$originalPwd" != *"$rootDir"* ]]; then
  echo "$originalPwd"
  echo "$rootDir"
  echo "${RED}The root directory, $rootDir, was not found"
  exit 1
fi

# If currentDir is not rootDir then run cdRoot
if [ "$currentDir" != "$rootDir" ]; then
  echo "${CYAN}You are not in the root of $rootDir, running cdRoot...${RESTORE}"
  . cdRoot "$rootDir"
  sleep 2
fi

find . -name "node_modules" -print -exec rm -rf '{}' +

echo ""
echo ""
echo ""

echo "${GREEN}All node_modules folders deleted! Running: pnpm install..."

pnpm install

echo "${GREEN}Done! Returning to original directory.${RESTORE}"

cd "$originalPwd" || exit
