#!/bin/bash

####################################
#   Print out info for aws-vault   #
####################################

source ~/bin/_colours

cat <<EOF
A handy tool for terminal based AWS access using aws-vault. It allows you to store your AWS credentials in your operating system's secure keystore and then use them from the command line. It also allows you to assume roles and use MFA.

+---------+----------------------------------------------+
|  Alias  |  Expression                                  |
+---------+----------------------------------------------+
|  av     |  aws-vault                                   |
|  ave    |  aws-vault exec                              |
|  avl    |  aws-vault login                             |
|  avll   |  aws-vault login -s                          |
|  avli   |  aws-vault login in private browsing window  |
|  avs    |  aws-vault server                            |
|  avsh   |  aws-vault exec \$1 -- zsh                    |
|  avp    |  list aws config / role ARNs                 |
+---------+----------------------------------------------+

See more at: https://github.com/blimmer/zsh-aws-vault
EOF
